[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_USE_PRODUCTION = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  headers = {Content-Type = "application/xml"}

[[redirects]]
  from = "/robots.txt" 
  to = "/robots.txt"
  status = 200
  headers = {Content-Type = "text/plain"}


# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"